/*
 *  NanoVNA-WebSaver -- the ported numerics checked against vectors
 *  generated by the desktop application and by numpy.
 *
 *  Copyright (C) 2020ff NanoVNA-Saver Authors
 *  Licensed under the GNU General Public License v3 or later.
 */

import { readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

import { assert, describe, it } from './harness.js';
import { complexArray, fft, ifft, fftshift, ifftshift } from '../js/util/fft.js';
import { blackman, hanning, kaiser, sum } from '../js/util/windows.js';
import { Calibration } from '../js/rf/calibration.js';
import { Datapoint } from '../js/rf/rftools.js';
import { maxima, minima, zeroCrossings } from '../js/rf/analytic.js';
import { computeTDR } from '../js/rf/tdr.js';

const HERE = dirname(fileURLToPath(import.meta.url));
const REF = JSON.parse(readFileSync(join(HERE, 'reference.json'), 'utf-8'));

const toComplexArray = (pairs) => {
  const out = complexArray(pairs.length);
  pairs.forEach(([re, im], i) => {
    out.re[i] = re;
    out.im[i] = im;
  });
  return out;
};

const assertComplexArray = (actual, expected, tol, label) => {
  assert.equal(actual.re.length, expected.length, `${label} length`);
  expected.forEach(([re, im], i) => {
    assert.close(actual.re[i], re, tol, `${label} re[${i}]`);
    assert.close(actual.im[i], im, tol, `${label} im[${i}]`);
  });
};

describe('fft against numpy', () => {
  const input = toComplexArray(REF.fft.input);

  it('matches numpy.fft.fft', () => {
    assertComplexArray(fft(input), REF.fft.fft, 1e-12, 'fft');
  });

  it('matches numpy.fft.ifft', () => {
    assertComplexArray(ifft(input), REF.fft.ifft, 1e-12, 'ifft');
  });

  it('zero pads like numpy.fft.ifft(a, n)', () => {
    assertComplexArray(ifft(input, 32), REF.fft.ifft32, 1e-12, 'ifft32');
  });

  it('matches numpy.fft.fftshift and ifftshift', () => {
    assertComplexArray(fftshift(input), REF.fft.fftshift, 1e-15, 'fftshift');
    assertComplexArray(ifftshift(input), REF.fft.ifftshift, 1e-15, 'ifftshift');
  });

  it('round trips a signal', () => {
    const back = ifft(fft(input));
    for (let i = 0; i < input.re.length; i += 1) {
      assert.close(back.re[i], input.re[i], 1e-12);
      assert.close(back.im[i], input.im[i], 1e-12);
    }
  });
});

describe('window functions against numpy', () => {
  const check = (actual, expected, label) => {
    assert.equal(actual.length, expected.length, `${label} length`);
    expected.forEach((v, i) => assert.close(actual[i], v, 1e-12, `${label}[${i}]`));
  };

  it('matches numpy.hanning and numpy.blackman', () => {
    check(hanning(8), REF.windows.hanning8, 'hanning');
    check(blackman(8), REF.windows.blackman8, 'blackman');
  });

  it('matches numpy.kaiser across beta values', () => {
    check(kaiser(8, 6), REF.windows.kaiser8_6, 'kaiser 6');
    check(kaiser(16, 13), REF.windows.kaiser16_13, 'kaiser 13');
    check(kaiser(8, 100), REF.windows.kaiser8_100, 'kaiser 100');
  });

  it('matches the kaiser amplitude correction factor', () => {
    assert.close(sum(kaiser(101, 6)), REF.windows.kaiser_corr_101_6, 1e-9);
  });
});

describe('calibration against the desktop solver', () => {
  const buildCalibration = () => {
    const cal = new Calibration();
    cal.calElement.shortState = 'IDEAL';
    cal.calElement.openState = 'IDEAL';
    cal.calElement.loadState = 'IDEAL';
    cal.calElement.throughIsIdeal = true;
    for (const name of ['short', 'open', 'load']) {
      cal.insert(
        name,
        REF.calibration.measured[name].map(([f, re, im]) => new Datapoint(f, re, im)),
      );
    }
    cal.calcCorrections();
    return cal;
  };

  it('solves the same error terms', () => {
    const cal = buildCalibration();
    const entries = cal.dataset.values();
    assert.equal(entries.length, REF.calibration.e_terms.length);
    REF.calibration.e_terms.forEach((row, i) => {
      const [freq, e00re, e00im, e11re, e11im, dEre, dEim] = row;
      assert.equal(entries[i].freq, freq);
      assert.close(entries[i].e00.re, e00re, 1e-12, `e00 re at ${freq}`);
      assert.close(entries[i].e00.im, e00im, 1e-12, `e00 im at ${freq}`);
      assert.close(entries[i].e11.re, e11re, 1e-12, `e11 re at ${freq}`);
      assert.close(entries[i].e11.im, e11im, 1e-12, `e11 im at ${freq}`);
      assert.close(entries[i].deltaE.re, dEre, 1e-12, `deltaE re at ${freq}`);
      assert.close(entries[i].deltaE.im, dEim, 1e-12, `deltaE im at ${freq}`);
    });
  });

  it('corrects a measurement identically', () => {
    const cal = buildCalibration();
    REF.calibration.dut_raw.forEach(([f, re, im], i) => {
      const out = cal.correct11(new Datapoint(f, re, im));
      const [, expRe, expIm] = REF.calibration.dut_corrected[i];
      assert.close(out.re, expRe, 1e-12, `corrected re at ${f}`);
      assert.close(out.im, expIm, 1e-12, `corrected im at ${f}`);
    });
  });

  it('recovers the reflection of the device under test', () => {
    const cal = buildCalibration();
    // The error terms are sampled at 21 frequencies and interpolated
    // onto 41, so the recovered value trails the true one; the desktop
    // implementation is out by up to 0.027 on this fixture for the same
    // reason. The exact agreement with it is asserted above.
    REF.calibration.dut_raw.forEach(([f, re, im], i) => {
      const out = cal.correct11(new Datapoint(f, re, im));
      const [, actualRe, actualIm] = REF.calibration.dut_actual[i];
      assert.close(out.re, actualRe, 0.03, `recovered re at ${f}`);
      assert.close(out.im, actualIm, 0.03, `recovered im at ${f}`);
    });
  });

  it('models non ideal calibration standards identically', () => {
    const cal = new Calibration();
    const el = cal.calElement;
    el.shortState = 'COEFF';
    el.openState = 'COEFF';
    el.loadState = 'COEFF';
    el.throughIsIdeal = false;
    el.throughLength = 100e-12;
    const methods = ['gammaShort', 'gammaOpen', 'gammaLoad', 'gammaThrough'];
    REF.gammas.forEach((row) => {
      const freq = row[0];
      methods.forEach((method, m) => {
        const [re, im] = row[m + 1];
        const value = cal[method](freq);
        assert.close(value.re, re, 1e-12, `${method} re at ${freq}`);
        assert.close(value.im, im, 1e-12, `${method} im at ${freq}`);
      });
    });
  });

  it('refuses to solve an incomplete calibration', () => {
    const cal = new Calibration();
    cal.insert('short', [new Datapoint(1e6, -1, 0)]);
    assert.throws(() => cal.calcCorrections());
  });
});

describe('peak finding against scipy', () => {
  it('finds the same maxima and minima on a clean sine', () => {
    assert.deepEqual(maxima(REF.analytic.sine), REF.analytic.sine_maxima);
    assert.deepEqual(minima(REF.analytic.sine), REF.analytic.sine_minima);
  });

  it('finds the same maxima and minima on a rippled signal', () => {
    assert.deepEqual(maxima(REF.analytic.noisy), REF.analytic.noisy_maxima);
    assert.deepEqual(minima(REF.analytic.noisy), REF.analytic.noisy_minima);
    assert.deepEqual(maxima(REF.analytic.noisy, 5.0), REF.analytic.noisy_maxima_thr);
  });

  it('finds the same zero crossings', () => {
    assert.deepEqual(zeroCrossings(REF.analytic.noisy), REF.analytic.zero_crossings);
  });
});

describe('tdr', () => {
  // an ideal lossless open ended line of a known length
  const line = (metres, vf, points = 201, fMax = 300e6) => {
    const c = 299792458 * vf;
    const out = [];
    for (let i = 0; i < points; i += 1) {
      const f = 1e6 + (i * (fMax - 1e6)) / (points - 1);
      const phase = (-2 * 2 * Math.PI * f * metres) / c;
      out.push(new Datapoint(Math.round(f), Math.cos(phase), Math.sin(phase)));
    }
    return out;
  };

  it('measures the length of a known line', () => {
    const result = computeTDR(line(1.0, 0.66), { velocityFactor: 0.66 });
    assert.close(result.cableLength, 1.0, 0.02, 'one metre');
    const longer = computeTDR(line(5.0, 0.66), { velocityFactor: 0.66 });
    assert.close(longer.cableLength, 5.0, 0.05, 'five metres');
  });

  it('reports a near 50 ohm step response for a matched load', () => {
    const matched = [];
    for (let i = 0; i < 201; i += 1) {
      matched.push(new Datapoint(1e6 + i * 1e6, 0, 0));
    }
    const result = computeTDR(matched, { format: '|Z| (lowpass)' });
    assert.close(result.stepResponseZ[0], 50, 1e-6);
    assert.close(result.stepResponseZ[100], 50, 1e-6);
  });

  it('supports every format and window', () => {
    const data = line(2.0, 0.66);
    for (const format of ['|Z| (lowpass)', 'S11 (lowpass)', 'VSWR (lowpass)',
                          'Refl (lowpass)', 'Refl (bandpass)']) {
      for (const window of ['hanning', 'blackman', 'kaiser0', 'kaiser6',
                            'kaiser13', 'kaiser100']) {
        const result = computeTDR(data, { format, window, velocityFactor: 0.66 });
        assert.ok(result !== null, `${format} / ${window}`);
        assert.ok(Number.isFinite(result.cableLength), `${format} / ${window} length`);
      }
    }
  });

  it('declines to compute without a span', () => {
    assert.equal(computeTDR([new Datapoint(1e6, 0, 0)]), null);
    const flat = [new Datapoint(1e6, 0, 0), new Datapoint(1e6, 0, 0)];
    assert.equal(computeTDR(flat), null);
  });
});
